import type { Event } from '../types/event.types.js';

const MOCK_EVENTS: Event[] = [
  {
    id: 1,
    title: 'Epic Hackathon',
    date: '2026-05-10T10:00:00Z',
    location: 'Moscow, Skolkovo Innovation Center',
    description: '36‑hour coding marathon for developers and designers',
    fullDescription: 'Join us for an intense 36‑hour hackathon where teams will build innovative solutions. Mentors from top tech companies will be available to help. Prizes for the best projects!',
    category: 'Technology',
    maxParticipants: 200,
    currentParticipants: 156,
    maxSpectators: 50,
    currentSpectators: 32,
    organizer: 'Tech Innovations Ltd',
    contactEmail: 'hackathon@techinnovations.com',
    contactPhone: '+7 (495) 123-45-67',
    requirements: 'Basic programming skills, laptop',
    price: 0,
    rewardsPoints: 500,
    duration: '36 hours',
    level: 'Intermediate',
    rules: 'Teams of 3–5 people, original code only, presentations in English',
    equipment: 'Laptop, power bank, headphones'
  },
  {
    id: 2,
    title: 'AI & Machine Learning Summit',
    date: '2026-06-15T09:00:00Z',
    location: 'Saint Petersburg, ExpoForum',
    description: 'Conference on the latest AI advancements and applications',
    fullDescription: 'Leading experts will discuss cutting‑edge AI research, practical ML implementations, and ethical considerations. Includes keynotes, workshops, and networking sessions.',
    category: 'Artificial Intelligence',
    maxParticipants: 300,
    currentParticipants: 285,
    maxSpectators: 100,
    currentSpectators: 76,
    organizer: 'Future Tech Association',
    contactEmail: 'ai-summit@futuretech.org',
    contactPhone: '+7 (812) 987-65-43',
    requirements: 'Interest in AI/ML, basic understanding of concepts',
    price: 2500,
    rewardsPoints: 800,
    duration: '2 days',
    level: 'Advanced',
    rules: 'No recording without permission, active participation in workshops'
  },
  {
    id: 3,
    title: 'Startup Pitch Competition',
    date: '2026-07-22T14:00:00Z',
    location: 'Kazan, IT Park',
    description: 'Pitch your startup idea to investors and win funding',
    fullDescription: 'Emerging startups present their business ideas to a panel of investors and industry experts. Top 3 teams receive investment offers and mentorship.',
    category: 'Entrepreneurship',
    maxParticipants: 50,
    currentParticipants: 42,
    maxSpectators: 200,
    currentSpectators: 180,
    organizer: 'Startup Hub Kazan',
    contactEmail: 'pitch@startuphub.kzn',
    contactPhone: '+7 (843) 555-12-34',
    requirements: 'Valid startup idea, pitch deck, team of 2–4 people',
    price: 1000,
    rewardsPoints: 1000,
    duration: '1 day',
    level: 'Beginner to Advanced',
    rules: '7‑minute pitch, 3‑minute Q&A, English or Russian language'
  },
  {
    id: 4,
    title: 'Web Development Workshop',
    date: '2026-08-05T11:00:00Z',
    location: 'Novosibirsk, IT Academy',
    description: 'Hands‑on workshop for front‑end and back‑end development',
    fullDescription: 'Practical sessions on HTML/CSS, JavaScript, and Node.js. Participants will build a complete web application with guidance from experienced developers.',
    category: 'Web Development',
    maxParticipants: 80,
    currentParticipants: 65,
    maxSpectators: 20,
    currentSpectators: 15,
    organizer: 'Code Masters Academy',
    contactEmail: 'workshop@codemasters.nsk',
    contactPhone: '+7 (383) 444-56-78',
    requirements: 'Laptop, basic coding knowledge',
    price: 1500,
    rewardsPoints: 600,
    duration: '8 hours',
    level: 'Beginner',
    rules: 'Follow instructor guidelines, share work for feedback'
  },
  {
    id: 5,
    title: 'Cybersecurity Challenge',
    date: '2026-09-18T08:00:00Z',
    location: 'Yekaterinburg, CyberSec Center',
    description: 'Capture‑the‑flag competition for security enthusiasts',
    fullDescription: 'Participants solve real‑world security challenges in categories like web exploitation, cryptography, and forensics. Prizes for top performers and certificates for all.',
    category: 'Security',
    maxParticipants: 120,
    currentParticipants: 98,
    maxSpectators: 30,
    currentSpectators: 25,
    organizer: 'SecureNet Solutions',
    contactEmail: 'ctf@securenet.ru',
    contactPhone: '+7 (343) 777-89-01',
    requirements: 'Knowledge of Linux, networking, and basic hacking tools',
    price: 500,
    rewardsPoints: 700,
    duration: '48 hours',
    level: 'Advanced',
    rules: 'No DDoS attacks, no sharing flags, individual or team of 2'
  },
  {
    id: 6,
    title: 'GameDev Jam',
    date: '2026-10-03T12:00:00Z',
    location: 'Vladivostok, Digital Arts Studio',
    description: 'Create a video game in 48 hours',
    fullDescription: 'Theme announced at start. Teams build games using any engine (Unity, Unreal, Godot). Judging based on creativity, gameplay, and technical execution.',
    category: 'Game Development',
    maxParticipants: 150,
    currentParticipants: 130,
    maxSpectators: 40,
    currentSpectators: 35,
    organizer: 'Pixel Studios',
    contactEmail: 'gamedev@pixelstudios.vl',
    contactPhone: '+7 (423) 666-78-90',
    requirements: 'Game engine experience, art/sound assets optional',
    price: 0,
    rewardsPoints: 900,
    duration: '48 hours',
    level: 'Intermediate',
    rules: 'Original assets, theme adherence, team of 1–4'
  },
  {
    id: 7,
    title: 'Data Science Bootcamp',
    date: '2026-11-12T09:30:00Z',
    location: 'Nizhny Novgorod, Data Lab',
    description: 'Intensive training in data analysis and visualization',
    fullDescription: 'Learn Python for data science, SQL, and Tableau. Hands‑on projects with real datasets. Certificate of completion provided.',
    category: 'Data Science',
    maxParticipants: 60,
    currentParticipants: 55,
    maxSpectators: 15,
    currentSpectators: 10,
    organizer: 'Analytics Guild',
    contactEmail: 'bootcamp@analytics.nn',
    contactPhone: '+7 (831) 333-44-55',
    requirements: 'Basic Python, curiosity about data',
    price: 3000,
    rewardsPoints: 850,
    duration: '5 days',
    level: 'Intermediate',
    rules: 'Complete all assignments, participate in group discussions'
  }
];

export const getAllEvents = async () => {
  return MOCK_EVENTS;
};

export const getEventById = async (id: number) => {
  return MOCK_EVENTS.find(event => event.id === id);
};